col MAX_LIMIT_VALUE for a30
select
cast (b.END_INTERVAL_TIME as date) SNAP_TIME,
--a.INSTANCE_NUMBER,
a.RESOURCE_NAME,
--CURRENT_UTILIZATION CURRENT_U,
max(MAX_UTILIZATION) MAX_UTILIZATION,
--max(trim(INITIAL_ALLOCATION)) INITIAL_ALLOC,
max(LIMIT_VALUE) MAX_LIMIT_VALUE
from DBA_HIST_RESOURCE_LIMIT a , DBA_HIST_SNAPSHOT b
where lower(a.RESOURCE_NAME) like '%' || lower('processes')  || '%'
and a.INSTANCE_NUMBER = b.INSTANCE_NUMBER
and a.SNAP_ID = b.SNAP_ID
group by
cast (b.END_INTERVAL_TIME as date),a.INSTANCE_NUMBER,RESOURCE_NAME
order by cast (b.END_INTERVAL_TIME as date)
/