SET LINE 9999 PAGES 9999
SET TAB OFF
SET COLSEP "|"
COL USERNAME FORMAT A15
COL SQL_STMT FORMAT A50
COL STATE FORMAT A10
COL MACHINE FORMAT A40
 
 
 
SET LINE 9999 PAGES 9999
SET TAB OFF
SET COLSEP "|"
COL USERNAME FORMAT A15
COL SQL_STMT FORMAT A50
COL STATE FORMAT A10
 
SELECT SUBSTR(A.USERNAME,1,15) USERNAME, A.SID, A.SERIAL#, 
       B.SQL_TEXT SQL_STMT, 
       TO_CHAR(A.LOGON_TIME,'DD-MM-YY HH24:MI')LOGON_TIME ,
       TO_CHAR(SYSDATE,'DD-MM-YY HH24:MI') CUR_TIME,
       --((TO_CHAR(SYSDATE,'HH24MI')-TO_CHAR(A.LOGON_TIME,'HH24MI'))*(60/100)) TIME_TAKEN_Mins,
       A.STATUS,D.SPID UNIX_PID
  FROM V$SESSION A,
       V$SQLAREA B,
       V$SESSION C,
       V$PROCESS D
WHERE B.SQL_TEXT NOT LIKE '%SELECT%SERIAL#%' 
   AND A.SQL_ADDRESS = B.ADDRESS(+)
   AND A.SID = C.SID
--AND A.USERNAME='CSMARTIDL' 
   AND A.PADDR = D.ADDR
--AND a.STATUS='INACTIVE'
ORDER BY ((TO_CHAR(SYSDATE,'HH24MI')-TO_CHAR(A.LOGON_TIME,'HH24MI'))*(60/100));